binary_build_commands: make build
build_root:
  from_repository: true
images:
- dockerfile_path: build/Dockerfile.ci
  to: windows-machine-config-operator-test
operator:
  bundles:
  - context_dir: .
    dockerfile_path: bundle.Dockerfile
  substitutions:
  - pullspec: REPLACE_IMAGE
    with: windows-machine-config-operator-test
promotion:
  name: "4.6"
  namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 600Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: lint
  commands: make lint
  container:
    from: src
- as: build
  commands: make build
  container:
    from: src
- as: unit
  commands: make unit
  container:
    from: src
- as: aws-e2e-operator
  steps:
    cluster_profile: aws
    env:
      OO_CHANNEL: 0.0.0
      OO_INSTALL_NAMESPACE: openshift-windows-machine-config-operator
      OO_PACKAGE: windows-machine-config-operator
      OO_TARGET_NAMESPACES: '!install'
    test:
    - ref: windows-e2e-operator-test
    workflow: optional-operators-ci-aws-ovn-hybrid
- as: azure-e2e-operator
  steps:
    cluster_profile: azure4
    env:
      OO_CHANNEL: 0.0.0
      OO_INSTALL_NAMESPACE: openshift-windows-machine-config-operator
      OO_PACKAGE: windows-machine-config-operator
      OO_TARGET_NAMESPACES: '!install'
    test:
    - ref: windows-e2e-operator-test
    workflow: optional-operators-ci-azure-ovn-hybrid
- as: aws-e2e-operator-with-custom-vxlan-port
  steps:
    cluster_profile: aws
    env:
      OO_CHANNEL: 0.0.0
      OO_INSTALL_NAMESPACE: openshift-windows-machine-config-operator
      OO_PACKAGE: windows-machine-config-operator
      OO_TARGET_NAMESPACES: '!install'
    test:
    - ref: windows-e2e-operator-test-with-custom-vxlan-port
    workflow: optional-operators-ci-aws-ovn-hybrid-custom-vxlan-port
- as: vsphere-e2e-operator
  steps:
    cluster_profile: vsphere
    env:
      OO_CHANNEL: 0.0.0
      OO_INSTALL_NAMESPACE: openshift-windows-machine-config-operator
      OO_PACKAGE: windows-machine-config-operator
      OO_TARGET_NAMESPACES: '!install'
    test:
    - ref: windows-e2e-operator-test-with-custom-vxlan-port
    workflow: optional-operators-ci-vsphere-ovn-hybrid
zz_generated_metadata:
  branch: release-4.6
  org: openshift
  repo: windows-machine-config-operator
